const ProductDB = [
	{
		companyName: "Suruchi",
		products: [
			{
				name: "Suruchi Classic Mirchi 500gm",
				weight: "500 gm",
				prodImg: "products/suruchi/suruchi classic mirchi.jpg",
				mrp: "",
				wholesalePrice: "",
				offer: "",
				stock: "100",
			},
		],
	},
	{
		companyName: "Vithoba",
		products: [
			{
				name: "Vithoba Ayu Manjan 15gm",
				weight: "15gm",
				prodImg: "products/vithoba/manjan",
				mrp: "10",
				wholesalePrice: "8.35",
				offer: "",
				stock: "10",
			},
			{
				name: "Vithoba Ayu Manjan 25gm",
				weight: "25gm",
				prodImg: "products/vithoba/manjan",
				mrp: "15",
				wholesalePrice: "12,63",
				offer: "",
				stock: "10",
			},
			{
				name: "Vithoba Ayur.Toothpaste",
				weight: "150gm",
				prodImg: "products/vithoba/ayurvedic toothpaste",
				mrp: "125",
				wholesalePrice: "110",
				offer: "",
				stock: "20",
			},
			{
				name: "Vithoba Ayurvedic Kesh Tel",
				weight: "100gm",
				prodImg: "products/vithoba/hair oil",
				mrp: "145",
				wholesalePrice: "123.25",
				offer: "",
				stock: "30",
			},
			{
				name: "Vithoba Handwash Apple 200ml",
				weight: "200ml",
				prodImg: "products/vithoba/apple hand wash",
				mrp: "104",
				wholesalePrice: "90",
				offer: "",
				stock: "30",
			},
			{
				name: "Vithoba Handwash Sandle 200ml",
				weight: "200ml",
				prodImg: "products/vithoba/hand wash sandle",
				mrp: "104",
				wholesalePrice: "90",
				offer: "",
				stock: "30",
			},
			{
				name: "Vithoba Keshratna Pure Heena",
				weight: "50",
				prodImg: "products/vithoba/heena",
				mrp: "30",
				wholesalePrice: "25.50",
				offer: "",
				stock: "20",
			},
			{
				name: "Vithoba Rootfix Natural 150gm",
				weight: "150gm",
				prodImg: "products/vithoba/rootfix",
				mrp: "90",
				wholesalePrice: "80",
				offer: "",
				stock: "20",
			},
			{
				name: "Vithoba Vajayanthi Soap",
				weight: "75gm",
				prodImg: "products/vithoba/soap",
				mrp: "50",
				wholesalePrice: "45.50",
				offer: "",
				stock: "30",
			},
		],
	},
	{
		companyName: "Rambandhu",
		products: [
			{
				name: "pickle",
				weight: "",
				prodImg: "",
				mrp: "",
				wholesalePrice: "",
				offer: "",
				stock: "",
			},
		],
	},
	{
		companyName: "Saprem Tea",
		products: [
			{
				name: "pickle",
				weight: "",
				prodImg: "",
				mrp: "",
				wholesalePrice: "",
				offer: "",
				stock: "",
			},
		],
	},
	{
		companyName: "Gujrat Tea",
		products: [
			{
				name: "Masala Tea 250gm",
				weight: "250gm",
				prodImg: "products/gujrat tea/masala tea 250 gm",
				mrp: "165",
				wholesalePrice: "153",
				offer: "",
				stock: "40",
			},
			{
				name: "Navchetan Dust 250gm",
				weight: "250gm",
				prodImg: "products/gujrat tea/navchetan dust 250gm",
				mrp: "75",
				wholesalePrice: "56",
				offer: "",
				stock: "40",
			},
			{
				name: "Navchetan Elaichi",
				weight: "10gm",
				prodImg: "products/gujrat tea/navchetan elaichi",
				mrp: "10",
				wholesalePrice: "7",
				offer: "",
				stock: "40",
			},
			{
				name: "Navchetan Leaf 1kg",
				weight: "1kg",
				prodImg: "products/gujrat tea/navchetan leaf 1kg",
				mrp: "220",
				wholesalePrice: "160",
				offer: "",
				stock: "40",
			},
			{
				name: "Navchetan Leaf 100gm",
				weight: "100gm",
				prodImg: "products/gujrat tea/navchetan leaf tea 100gm",
				mrp: "20",
				wholesalePrice: "17",
				offer: "",
				stock: "40",
			},
			{
				name: "Navchetan Tea ",
				weight: "250gm",
				prodImg: "products/gujrat tea/navchetan tea 250gm",
				mrp: "55",
				wholesalePrice: "39",
				offer: "",
				stock: "40",
			},
			{
				name: "Navchetan dust 5k",
				weight: "5kg",
				prodImg: "products/gujrat tea/navchetan dust 5k",
				mrp: "165",
				wholesalePrice: "145",
				offer: "",
				stock: "40",
			},
			{
				name: "Mili Leaf 1kg",
				weight: "1kg",
				prodImg: "products/gujrat tea/mili leaf 1kg",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Mili Leaf 250gm",
				weight: "250gm",
				prodImg: "products/gujrat tea/mili leaf 250gm",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Mili Leaf 5kg",
				weight: "5kg",
				prodImg: "products/gujrat tea/mili leaf 5kg",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Green Tea",
				weight: "100gm",
				prodImg: "products/gujrat tea/green tea 100gm",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "110",
			},
			{
				name: "Leaf 1kg Pouch",
				weight: "1kg",
				prodImg: "products/gujrat tea/leaf tea 1kg pouch",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Leaf 250gm Pouch",
				weight: "250gm",
				prodImg: "products/gujrat tea/leaf tea 250gm",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Leaf 250gm Pouch",
				weight: "250gm",
				prodImg: "products/gujrat tea/leaf tea 250gm",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Leaf Carton 250",
				weight: "250gm",
				prodImg: "products/gujrat tea/leaf carton 250 gm",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Leaf Carton 500",
				weight: "500gm",
				prodImg: "products/gujrat tea/leaf carton 500gm",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
			{
				name: "Sugar 1kg Pouch",
				weight: "1kg",
				prodImg: "products/gujrat tea/sugar 1kg",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "40",
			},
		],
	},
	{
		companyName: "Mangalam Camphor",
		products: [
			{
				name: "Mangalam Camphor",
				weight: "50gm",
				prodImg: "products/mangalam camphor/50 gm",
				mrp: "100",
				wholesalePrice: "55",
				offer: "",
				stock: "58",
			},
			{
				name: "Mangalam Cones Bhimseni",
				weight: "60gm",
				prodImg: "products/mangalam camphor/bhimseni cone 60gm",
				mrp: "199",
				wholesalePrice: "130",
				offer: "",
				stock: "3",
			},
			{
				name: "Mangalam Cones Jasmine",
				weight: "60gm",
				prodImg: "products/mangalam camphor/jasmine",
				mrp: "199",
				wholesalePrice: "130",
				offer: "",
				stock: "5",
			},
			{
				name: "Mangalam Cones Lavender",
				weight: "60gm",
				prodImg: "products/mangalam camphor/lavendar cone",
				mrp: "130",
				wholesalePrice: "199",
				offer: "",
				stock: "3",
			},
			{
				name: "Mangalam Cones Mogra",
				weight: "60gm",
				prodImg: "products/mangalam camphor/mogra cone",
				mrp: "199",
				wholesalePrice: "130",
				offer: "",
				stock: "4",
			},
			{
				name: "Mangalam Cones Rose",
				weight: "60gm",
				prodImg: "products/mangalam camphor/rose cone",
				mrp: "199",
				wholesalePrice: "130",
				offer: "",
				stock: "4",
			},
			{
				name: "Mangalam Cones Sandalwood",
				weight: "60gm",
				prodImg: "products/mangalam camphor/sandalwood cone",
				mrp: "199",
				wholesalePrice: "130",
				offer: "",
				stock: "4",
			},
		],
	},
	{
		companyName: "Shanti Spices",
		products: [
			{
				name: "Ajwain",
				weight: "10gm",
				prodImg: "products/shanti spices/10gm-khandeshi-ajwain-seeds",
				mrp: "10",
				wholesalePrice: "7.40",
				offer: "",
				stock: "10",
			},
			{
				name: "Kimsa Dates",
				weight: "400gm",
				prodImg: "products/shanti spices/kimsa dates 400gm",
				mrp: "240",
				wholesalePrice: "168",
				offer: "",
				stock: "10",
			},
			{
				name: "Chicken Masala",
				weight: "50gm",
				prodImg: "products/shanti spices/chicken masala",
				mrp: "35",
				wholesalePrice: "28.50",
				offer: "",
				stock: "10",
			},
			{
				name: "Chicken Masala",
				weight: "10gm",
				prodImg: "products/shanti spices/chicken",
				mrp: "10",
				wholesalePrice: "8.50",
				offer: "",
				stock: "10",
			},
			{
				name: "Deg Khada Masala",
				weight: "250gm",
				prodImg: "products/shanti spices/deg khada masala 250gm",
				mrp: "40",
				wholesalePrice: "25.50",
				offer: "",
				stock: "730",
			},
			{
				name: "Mix Khada Masala",
				weight: "250gm",
				prodImg: "products/shanti spices/special khada masala 250gm",
				mrp: "50",
				wholesalePrice: "30.40",
				offer: "",
				stock: "10",
			},
			{
				name: "Khandeshi Khada Masala",
				weight: "10gm",
				prodImg: "products/shanti spices/khada masala",
				mrp: "20",
				wholesalePrice: "16.50",
				offer: "",
				stock: "10",
			},
			{
				name: "Mutton Masala",
				weight: "200gm",
				prodImg: "products/shanti spices/mutton masala",
				mrp: "80",
				wholesalePrice: "40.40",
				offer: "",
				stock: "141",
			},
			{
				name: "Premium Khajur",
				weight: "400gm",
				prodImg: "products/shanti spices/khajoor irani 400gm",
				mrp: "90",
				wholesalePrice: "63",
				offer: "",
				stock: "10",
			},
			{
				name: "Desert king Khajur",
				weight: "400gm",
				prodImg: "products/shanti spices/desert king khajoor 400gm",
				mrp: "90",
				wholesalePrice: "63",
				offer: "",
				stock: "10",
			},
			{
				name: "Rajgira Aata",
				weight: "200gm",
				prodImg: "products/shanti spices/rajgira aata",
				mrp: "67",
				wholesalePrice: "49",
				offer: "",
				stock: "10",
			},
			{
				name: "Singada Aata ",
				weight: "200gm",
				prodImg: "products/shanti spices/singada aata 200gm",
				mrp: "62",
				wholesalePrice: "53",
				offer: "",
				stock: "10",
			},
			{
				name: "Upawas Bhajani",
				weight: "200gm",
				prodImg: "products/shanti spices/khas khas 5rps",
				mrp: "5",
				wholesalePrice: "2",
				offer: "",
				stock: "10",
			},
			{
				name: "Kharik Powder",
				weight: "500gm",
				prodImg: "products/shanti spices/kharik powder",
				mrp: "90",
				wholesalePrice: "63",
				offer: "",
				stock: "10",
			},
		],
	},
	{
		companyName: "Bhavika Gruh Udyog",
		products: [
			{
				name: "Kala Namak",
				weight: "100gm",
				prodImg: "products/bhavika gruh udyog/kala namak",
				mrp: "10",
				wholesalePrice: "7",
				offer: "",
				stock: "10",
			},
			{
				name: "Nachni Satva ",
				weight: "200gm",
				prodImg: "products/bhavika gruh udyog/nachni satva",
				mrp: "45",
				wholesalePrice: "36",
				offer: "",
				stock: "38",
			},
			{
				name: "Ros.Rajgira Aata",
				weight: "200gm",
				prodImg: "products/bhavika gruh udyog/rajgira aata",
				mrp: "60",
				wholesalePrice: "28.60",
				offer: "",
				stock: "15",
			},
			{
				name: "Ros.Singada Aata",
				weight: "200gm",
				prodImg: "products/bhavika gruh udyog/singada aata",
				mrp: "60",
				wholesalePrice: "44",
				offer: "",
				stock: "23",
			},
			{
				name: "Roshni Idli Rawa",
				weight: "500gm",
				prodImg: "products/bhavika gruh udyog/idli rawa",
				mrp: "32",
				wholesalePrice: "24",
				offer: "",
				stock: "13",
			},
			{
				name: "Roshni Maida",
				weight: "500gm",
				prodImg: "products/bhavika gruh udyog/maida",
				mrp: "35",
				wholesalePrice: "26",
				offer: "",
				stock: "12",
			},
			{
				name: "Roshni Upma Rawa",
				weight: "500gm",
				prodImg: "products/bhavika gruh udyog/upma rawa",
				mrp: "40",
				wholesalePrice: "27",
				offer: "",
				stock: "30",
			},
			{
				name: "Senda Namak",
				weight: "1kg",
				prodImg: "products/bhavika gruh udyog/senda namak",
				mrp: "70",
				wholesalePrice: "57",
				offer: "",
				stock: "35",
			},
			{
				name: "Senda Namak",
				weight: "100",
				prodImg: "products/bhavika gruh udyog/senda namak",
				mrp: "15",
				wholesalePrice: "7",
				offer: "",
				stock: "32",
			},
		],
	},
	{
		companyName: "Green Planet",
		products: [
			{
				name: "Green Planet Aloe Vera Juice 1l",
				weight: "1l",
				prodImg: "products/greenplanet/aloevera juice",
				mrp: "799",
				wholesalePrice: "685",
				offer: "",
				stock: "10",
			},
			{
				name: "Green Planet Aloe Vera Skin Cream 70gms",
				weight: "70gms",
				prodImg: "products/greenplanet/aloevera cream",
				mrp: "299",
				wholesalePrice: "241",
				offer: "",
				stock: "50",
			},
			{
				name: "Green Planet Alovira Shampoo",
				weight: "",
				prodImg: "products/greenplanet/aloevera shampoo",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "60",
			},
			{
				name: "Green Planet Bhoomi Power 4kg",
				weight: "4kg",
				prodImg: "products/greenplanet/bhoomi power",
				mrp: "1100",
				wholesalePrice: "800",
				offer: "",
				stock: "10",
			},
			{
				name: "Green Planet Bloom",
				weight: "1l",
				prodImg: "products/greenplanet/bloom",
				mrp: "750",
				wholesalePrice: "610",
				offer: "",
				stock: "28",
			},
			{
				name: "Green Planet Cleansing Milk",
				weight: "200ml",
				prodImg: "products/greenplanet/cleansing milk",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "10",
			},
			{
				name: "Green Planet Digester",
				weight: "200ml",
				prodImg: "products/greenplanet/digester",
				mrp: "300",
				wholesalePrice: "236",
				offer: "",
				stock: "10",
			},
			{
				name: "Green Planet Energy Powder Orange",
				weight: "250gm",
				prodImg: "products/greenplanet/power energy",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "10",
			},
			{
				name: "Green Planet Fairness Cream Men 100gm",
				weight: "100gm",
				prodImg: "products/greenplanet/men cream",
				mrp: "330",
				wholesalePrice: "255",
				offer: "",
				stock: "30",
			},
			{
				name: "Green Planet Fruiter",
				weight: "500ml",
				prodImg: "products/greenplanet/fruiter",
				mrp: "2300",
				wholesalePrice: "1800",
				offer: "",
				stock: "30",
			},
			{
				name: "Green Planet Garlic Softgels 60",
				weight: "60ml",
				prodImg: "products/greenplanet/garlic softgel",
				mrp: "430",
				wholesalePrice: "325",
				offer: "",
				stock: "60",
			},
			{
				name: "Green Planet Gasi Norm 60 Tabs ",
				weight: "60 Tabs",
				prodImg: "products/greenplanet/gasi norm",
				mrp: "400",
				wholesalePrice: "330",
				offer: "",
				stock: "12",
			},
			{
				name: "Green Planet Grow",
				weight: "250ml",
				prodImg: "products/greenplanet/grow",
				mrp: "350",
				wholesalePrice: "250",
				offer: "",
				stock: "13",
			},
			{
				name: "Green Planet Immune Booster Kadha 100gm",
				weight: "100gm",
				prodImg: "products/greenplanet/immune booster",
				mrp: "275",
				wholesalePrice: "250",
				offer: "",
				stock: "4",
			},
			{
				name: "Green Planet My C Chew 30 Tabs",
				weight: "30 Tabs",
				prodImg: "products/greenplanet/c chew",
				mrp: "225",
				wholesalePrice: "165",
				offer: "",
				stock: "50",
			},
			{
				name: "Green Planet Natro King",
				weight: "250ml",
				prodImg: "products/greenplanet/nitro king",
				mrp: "300",
				wholesalePrice: "220",
				offer: "",
				stock: "20",
			},
			{
				name: "Green Planet Neem Face Wash 100gms",
				weight: "100gms",
				prodImg: "products/greenplanet/neem fash wash",
				mrp: "340",
				wholesalePrice: "205",
				offer: "",
				stock: "20",
			},
			{
				name: "Green Planet Noni Neut Juice 500ml",
				weight: "500ml",
				prodImg: "products/greenplanet/garlic softgel",
				mrp: "950",
				wholesalePrice: "690",
				offer: "",
				stock: "19",
			},
			{
				name: "Green Planet Omega 36960 Softgels",
				weight: "60ml",
				prodImg: "products/greenplanet/omega",
				mrp: "690",
				wholesalePrice: "570",
				offer: "",
				stock: "8",
			},
			{
				name: "Green Planet Pesto Hit",
				weight: "250ml",
				prodImg: "products/greenplanet/pesto hit",
				mrp: "1400",
				wholesalePrice: "1200",
				offer: "",
				stock: "20",
			},
			{
				name: "Green Planet PM Stress Off",
				weight: "200gms",
				prodImg: "products/greenplanet/stress out",
				mrp: "125",
				wholesalePrice: "105",
				offer: "",
				stock: "16",
			},
			{
				name: "Green Planet Red Aloe Vera Juice ",
				weight: "500ml",
				prodImg: "products/greenplanet/red juice",
				mrp: "699",
				wholesalePrice: "570",
				offer: "",
				stock: "40",
			},
			{
				name: "Green Planet Seed Treatment",
				weight: "250ml",
				prodImg: "products/greenplanet/seed treatment",
				mrp: "1150",
				wholesalePrice: "830",
				offer: "",
				stock: "36",
			},
			{
				name: "Green Planet Spread All 90",
				weight: "1l",
				prodImg: "products/greenplanet/spread all 90",
				mrp: "1075",
				wholesalePrice: "875",
				offer: "",
				stock: "80",
			},
			{
				name: "Green Planet Super Power Capsule 40caps",
				weight: "40caps",
				prodImg: "products/greenplanet/super power",
				mrp: "600",
				wholesalePrice: "425",
				offer: "",
				stock: "23",
			},
			{
				name: "Green Planet Sweet Dew 10ml",
				weight: "10ml",
				prodImg: "products/greenplanet/sweet dew",
				mrp: "150",
				wholesalePrice: "130",
				offer: "",
				stock: "23",
			},
			{
				name: "Green Planet Triras Aloe Jamun Karela",
				weight: "500ml",
				prodImg: "products/greenplanet/triras",
				mrp: "0",
				wholesalePrice: "0",
				offer: "",
				stock: "2",
			},
			{
				name: "Green Planet Tulsi Drops 40ml",
				weight: "40ml",
				prodImg: "products/greenplanet/tulsi drops",
				mrp: "375",
				wholesalePrice: "270",
				offer: "",
				stock: "12",
			},
			{
				name: "Green Planet Viro Hit",
				weight: "250ml",
				prodImg: "products/greenplanet/viro",
				mrp: "1490",
				wholesalePrice: "1190",
				offer: "",
				stock: "23",
			},
			{
				name: "Green Planet Vit N Fit Dietary Supp.30T",
				weight: "30T",
				prodImg: "products/greenplanet/vit n fit",
				mrp: "499",
				wholesalePrice: "409",
				offer: "",
				stock: "12",
			},
			{
				name: "Green Planet Vit-Min Shake Vanilla 500",
				weight: "500ml",
				prodImg: "products/greenplanet/vit min shake",
				mrp: "799",
				wholesalePrice: "785",
				offer: "",
				stock: "10",
			},
			{
				name: "Green Planet Vitamin A E C 60",
				weight: "90 Tabs",
				prodImg: "products/greenplanet/vitamins",
				mrp: "520",
				wholesalePrice: "425",
				offer: "",
				stock: "16",
			},
		],
	},
	{
		companyName: "Gowardhan",
		products: [
			{
				name: "Gowardhan Frozen Paneer Cubes",
				weight: "200gm",
				prodImg: "products/gowardhan/paneer cubes",
				mrp: "97",
				wholesalePrice: "91.70",
				offer: "",
				stock: "40",
			},
			{
				name: "Gowardhan Ghee 5L Jar",
				weight: "5L",
				prodImg: "products/gowardhan/500ml ghee",
				mrp: "3695",
				wholesalePrice: "3422",
				offer: "",
				stock: "40",
			},
			{
				name: "Gowardhan Ghee 5L Tin",
				weight: "5L",
				prodImg: "products/gowardhan/ghee tin",
				mrp: "3475",
				wholesalePrice: "3378",
				offer: "",
				stock: "40",
			},
			{
				name: "Gowardhan Ghee Cont",
				weight: "2L",
				prodImg: "products/gowardhan/ghee 2ltr",
				mrp: "1158",
				wholesalePrice: "1107",
				offer: "",
				stock: "40",
			},
			{
				name: "Gowardhan Ghee Jar",
				weight: "750ml",
				prodImg: "products/gowardhan/ghee 750 ml",
				mrp: "539",
				wholesalePrice: "502",
				offer: "",
				stock: "40",
			},
			{
				name: "Gowardhan Topp Up Milk Elaichi",
				weight: "200ml",
				prodImg: "products/gowardhan/topup milk elaichi",
				mrp: "30",
				wholesalePrice: "20",
				offer: "",
				stock: "40",
			},
			{
				name: "Gowardhan Topp Up Milk Rose",
				weight: "200ml",
				prodImg: "products/gowardhan/topup milk rose",
				mrp: "25",
				wholesalePrice: "20",
				offer: "",
				stock: "40",
			},
		],
	},
	{
		companyName: "Wikiefield",
		products: [
			{
				name: " Wikiefield Instant Pasta Cheezy",
				weight: "70gm",
				prodImg: "products/weikfield/instant pasta cheezy",
				mrp: "25",
				wholesalePrice: "20.50",
				offer: "",
				stock: "20",
			},
			{
				name: "Wikiefield Baking PW",
				weight: "50gm",
				prodImg: "products/weikfield/baking powder",
				mrp: "25",
				wholesalePrice: "21.20",
				offer: "",
				stock: "30",
			},
			{
				name: " Wikiefield Button mushrooms",
				weight: "800",
				prodImg: "products/weikfield/button mushrooms",
				mrp: "175",
				wholesalePrice: "108",
				offer: "",
				stock: "30",
			},
			{
				name: "Wikiefield Chef Basket Pasta Elbow ",
				weight: "500gm",
				prodImg: "products/weikfield/basket pasta elbow",
				mrp: "175",
				wholesalePrice: "154",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Chef Basket Pasta Macroni",
				weight: "180gm",
				prodImg: "products/weikfield/basket pasta macroni",
				mrp: "25",
				wholesalePrice: "21.50",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Chef Basket Pasta Masala",
				weight: "7gm",
				prodImg: "products/weikfield/basket pasta masala",
				mrp: "3.80",
				wholesalePrice: "5",
				offer: "",
				stock: "100",
			},
			{
				name: "Wikiefield Chef Basket Pasta Fusili",
				weight: "500gm",
				prodImg: "products/weikfield/basket pasta fusilli",
				mrp: "156.50",
				wholesalePrice: "175",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Chef Basket Pasta Penne",
				weight: "500gm",
				prodImg: "products/weikfield/basket pasta penne",
				mrp: "175",
				wholesalePrice: "156.50",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Cooker Cake Mix Chocolate",
				weight: "150gm",
				prodImg: "products/weikfield/cooker cake chocolate",
				mrp: "75",
				wholesalePrice: "62",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Cooker Cake Mix Vanila",
				weight: "150gm",
				prodImg: "products/weikfield/cooker cake mix vanilla",
				mrp: "95",
				wholesalePrice: "58",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Cornflour",
				weight: "50kg",
				prodImg: "products/weikfield/cornflour",
				mrp: "3400",
				wholesalePrice: "3400",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Custars PW Vanilla",
				weight: "150gm",
				prodImg: "products/weikfield/custard pwd vanilla",
				mrp: "42",
				wholesalePrice: "37.40",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Falooda Mix Kesar Pista",
				weight: "200gm",
				prodImg: "products/weikfield/falooda kesar pista",
				mrp: "57",
				wholesalePrice: "48",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Falooda Mix Mango",
				weight: "200gm",
				prodImg: "products/weikfield/falooda mix mango",
				mrp: "57",
				wholesalePrice: "48",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Falooda Mix Rose",
				weight: "200gm",
				prodImg: "products/weikfield/falooda mix rose",
				mrp: "57",
				wholesalePrice: "48",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Falooda Mix Strawberry",
				weight: "200gm",
				prodImg: "products/weikfield/falooda mix strawberry",
				mrp: "55",
				wholesalePrice: "48",
				offer: "",
				stock: "40",
			},
			{
				name: "Wikiefield Instant Pasta Masala",
				weight: "77gm",
				prodImg: "products/weikfield/instant pasta masala",
				mrp: "25",
				wholesalePrice: "20.50",
				offer: "",
				stock: "40",
			},
		],
	},
	{
		companyName: "Recon",
		products: [
			{
				name: "Recon Tez Mustard Oil",
				weight: "200ml",
				prodImg: "products/recon/tez mustard oil 200ml",
				mrp: "54",
				wholesalePrice: "43",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tez Mustard Oil",
				weight: "500ml",
				prodImg: "products/recon/tez mustard oil 500ml",
				mrp: "126",
				wholesalePrice: "102",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Agarbatti Amm Advaita",
				weight: "250gm",
				prodImg: "products/recon/agarbatti lavender 250gm",
				mrp: "130",
				wholesalePrice: "79",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Agarbatti Amm Prathana",
				weight: "130ml",
				prodImg: "products/recon/agarbatti prarthana 130gm",
				mrp: "75",
				wholesalePrice: "69",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Amm Lamp Oil",
				weight: "150ml",
				prodImg: "products/recon/lamp oil 150ml",
				mrp: "37",
				wholesalePrice: "29",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Amm Lamp Oil",
				weight: "450ml",
				prodImg: "products/recon/lamp oil 450ml",
				mrp: "110",
				wholesalePrice: "70",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Amm Lamp Oil",
				weight: "900ml",
				prodImg: "products/recon/lamp oil 900ml",
				mrp: "210",
				wholesalePrice: "131",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Coconut Oil",
				weight: "100ml",
				prodImg: "products/recon/coconut oil 100ml",
				mrp: "39",
				wholesalePrice: "28",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Coconut Oil",
				weight: "175ml",
				prodImg: "products/recon/coconut oil 175 ml",
				mrp: "69",
				wholesalePrice: "50",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Coconut Oil",
				weight: "500ml",
				prodImg: "products/recon/coconut oil 500ml",
				mrp: "199",
				wholesalePrice: "140",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tez Mustard Oil",
				weight: "144ml",
				prodImg: "products/recon/tez mustard oil 144",
				mrp: "27",
				wholesalePrice: "23,70",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tez Mustard Oil",
				weight: "1l",
				prodImg: "products/recon/tez mustard oil 1lte",
				mrp: "197",
				wholesalePrice: "148",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tez Mustard Oil",
				weight: "200ml",
				prodImg: "products/recon/tez mustard oil 200ml",
				mrp: "44",
				wholesalePrice: "39",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tez Mustard Oil",
				weight: "500ml",
				prodImg: "products/recon/tez mustard oil 500ml",
				mrp: "114",
				wholesalePrice: "90.60",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tilsona Gold Til Oil",
				weight: "1l",
				prodImg: "products/recon/tilsona oil 1ltr",
				mrp: "435",
				wholesalePrice: "380",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tilsona Gold Til Oil",
				weight: "200ml",
				prodImg: "products/recon/tilsona oil 200ml",
				mrp: "100",
				wholesalePrice: "88",
				offer: "",
				stock: "40",
			},
			{
				name: "Recon Tilsona Gold Til Oil",
				weight: "500ml",
				prodImg: "products/recon/tilsona oil 500ml",
				mrp: "230",
				wholesalePrice: "202",
				offer: "",
				stock: "40",
			},
		],
	},
];

export default ProductDB;
